#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Spec 003

set -e

echo "========================================"
echo "n8n Quo Node Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# ============================================
# SETUP DEVELOPMENT ENVIRONMENT
# ============================================

echo ""
echo "Installing dependencies..."
npm install

if [ $? -eq 0 ]; then
    echo -e "${GREEN}Dependencies installed successfully${NC}"
else
    echo -e "${RED}Failed to install dependencies${NC}"
    exit 1
fi

echo ""
echo "Starting TypeScript watch mode..."
npm run dev &
DEV_PID=$!

echo -e "${GREEN}TypeScript compiler running in watch mode (PID: $DEV_PID)${NC}"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Development Commands:"
echo "  Build:        npm run build"
echo "  Watch:        npm run dev (already running)"
echo "  Lint:         npm run lint"
echo "  Lint & Fix:   npm run lintfix"
echo "  Format:       npm run format"
echo ""
echo "TypeScript compiler is watching for changes..."
echo "Press Ctrl+C to stop"
echo ""

# Keep script running
wait $DEV_PID
